export const PROJECT_VISIBILITY = {
  PUBLIC: "PUBLIC", // visible to everyone logged in or not, logged in users can create issues, comment but only edit issues they created
  SEMI_PUBLIC: "SEMI_PUBLIC", // visible to logged in users, users can create issues, comment but only edit issues they created
  SEMI_PROTECTED: "SEMI_PROTECTED", // visible to everyone, but only members can create issues, comment and edit issues
  PROTECTED: "PROTECTED", // visible to logged in users, but only members can create issues, comment and edit issues
  PRIVATE: "PRIVATE", // only visible to members of the project, users can create issues, comment but only edit issues they created
} as const;

export const USER_PROJECT_ROLE = {
  OWNER: "OWNER", // can do everything
  ADMIN: "ADMIN", // can do everything except delete the project
  QA: "QA", // can see, edit and create issues
  CONTRIBUTOR: "CONTRIBUTOR", // can see, edit and create issues
  VIEWER: "VIEWER", // can see issues and comments
  REPORTER: "REPORTER", // can see and create issues but not edit there own issues
} as const;

export const SETTING_SCOPE = {
  GLOBAL: "GLOBAL",
  PROJECT: "PROJECT",
  USER: "USER",
} as const;

export const USER_ISSUE_ROLE = {
  CREATOR: "CREATOR", // created the issue
  ASSIGNEE: "ASSIGNEE", // responsible for the issue
  REVIEWER: "REVIEWER", // responsible for the review of the issue
  WATCHER: "WATCHER", // responsible for the watching of the issue
} as const;

export const ATTACHMENT_TYPE = {
  IMAGE: "IMAGE",
  VIDEO: "VIDEO",
  AUDIO: "AUDIO",
  DOCUMENT: "DOCUMENT",
  OTHER: "OTHER",
  TEXT: "TEXT",
} as const;

export const CUSTOM_FIELD_TYPE = {
  TEXT: "TEXT",
  TEXT_AREA: "TEXT_AREA",
  NUMBER: "NUMBER",
  DATE: "DATE",
  BOOLEAN: "BOOLEAN",
  LINK: "LINK",
  USER: "USER",
  USER_LIST: "USER_LIST",
  SELECT: "SELECT",
  MULTI_SELECT: "MULTI_SELECT",
  FILE: "FILE",
  STATE: "STATE",
  CALCULATED: "CALCULATED",
  DATE_RANGE: "DATE_RANGE",
  DATE_TIME: "DATE_TIME",
  DATE_TIME_RANGE: "DATE_TIME_RANGE",
  TIME: "TIME",
  TIME_RANGE: "TIME_RANGE",
} as const;

export const OPERATORS = {
  EQUALS: "EQUALS",
  NOT_EQUALS: "NOT_EQUALS",
  CONTAINS: "CONTAINS",
  STARTS_WITH: "STARTS_WITH",
  ENDS_WITH: "ENDS_WITH",
  NOT_CONTAINS: "NOT_CONTAINS",
  NOT_STARTS_WITH: "NOT_STARTS_WITH",
  NOT_ENDS_WITH: "NOT_ENDS_WITH",
  LESS_THAN: "LESS_THAN",
  GREATER_THAN: "GREATER_THAN",
  LESS_THAN_OR_EQUALS: "LESS_THAN_OR_EQUALS",
  GREATER_THAN_OR_EQUALS: "GREATER_THAN_OR_EQUALS",
  IS_IN: "IS_IN",
  IS_NOT_IN: "IS_NOT_IN",
  IS_EMPTY: "IS_EMPTY",
  IS_NOT_EMPTY: "IS_NOT_EMPTY",
  NONE_SELECTED: "NONE_SELECTED",
  ANY_SELECTED: "ANY_SELECTED",
  COUNT_EQUALS: "COUNT_EQUALS",
  COUNT_NOT_EQUALS: "COUNT_NOT_EQUALS",
  COUNT_LESS_THAN: "COUNT_LESS_THAN",
  COUNT_GREATER_THAN: "COUNT_GREATER_THAN",
  COUNT_LESS_THAN_OR_EQUALS: "COUNT_LESS_THAN_OR_EQUALS",
  COUNT_GREATER_THAN_OR_EQUALS: "COUNT_GREATER_THAN_OR_EQUALS",
  WITH_IN: "WITH_IN",
  OUTSIDE_OF: "OUTSIDE_OF",
} as const;

export const CUSTOM_FIELD_DEPENDENCY_OPERATOR = {
  AND: "AND",
  OR: "OR",
} as const;

export const ISSUE_AUDIT_ACTION = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
} as const;

export const ISSUE_FIELD_COMPATIBLE_OPERATORS = {
  TEXT: [
    OPERATORS.EQUALS,
    OPERATORS.NOT_EQUALS,
    OPERATORS.CONTAINS,
    OPERATORS.STARTS_WITH,
    OPERATORS.ENDS_WITH,
    OPERATORS.NOT_CONTAINS,
    OPERATORS.NOT_STARTS_WITH,
    OPERATORS.NOT_ENDS_WITH,
    OPERATORS.COUNT_EQUALS,
    OPERATORS.COUNT_NOT_EQUALS,
    OPERATORS.COUNT_LESS_THAN,
    OPERATORS.COUNT_GREATER_THAN,
    OPERATORS.COUNT_LESS_THAN_OR_EQUALS,
    OPERATORS.COUNT_GREATER_THAN_OR_EQUALS,
  ],
  NUMBER: [
    OPERATORS.EQUALS,
    OPERATORS.NOT_EQUALS,
    OPERATORS.LESS_THAN,
    OPERATORS.GREATER_THAN,
    OPERATORS.LESS_THAN_OR_EQUALS,
    OPERATORS.GREATER_THAN_OR_EQUALS,
  ],
  DATE: [
    OPERATORS.EQUALS,
    OPERATORS.NOT_EQUALS,
    OPERATORS.LESS_THAN,
    OPERATORS.GREATER_THAN,
    OPERATORS.LESS_THAN_OR_EQUALS,
    OPERATORS.GREATER_THAN_OR_EQUALS,
  ],
  DATE_RANGE: [
    OPERATORS.EQUALS,
    OPERATORS.NOT_EQUALS,
    OPERATORS.LESS_THAN,
    OPERATORS.GREATER_THAN,
    OPERATORS.LESS_THAN_OR_EQUALS,
    OPERATORS.GREATER_THAN_OR_EQUALS,
    OPERATORS.WITH_IN,
    OPERATORS.OUTSIDE_OF,
  ],
  DATE_TIME: [
    OPERATORS.EQUALS,
    OPERATORS.NOT_EQUALS,
    OPERATORS.LESS_THAN,
    OPERATORS.GREATER_THAN,
    OPERATORS.LESS_THAN_OR_EQUALS,
    OPERATORS.GREATER_THAN_OR_EQUALS,
  ],
  DATE_TIME_RANGE: [
    OPERATORS.EQUALS,
    OPERATORS.NOT_EQUALS,
    OPERATORS.LESS_THAN,
    OPERATORS.GREATER_THAN,
    OPERATORS.LESS_THAN_OR_EQUALS,
    OPERATORS.GREATER_THAN_OR_EQUALS,
    OPERATORS.WITH_IN,
    OPERATORS.OUTSIDE_OF,
  ],
  TIME: [
    OPERATORS.EQUALS,
    OPERATORS.NOT_EQUALS,
    OPERATORS.LESS_THAN,
    OPERATORS.GREATER_THAN,
    OPERATORS.LESS_THAN_OR_EQUALS,
    OPERATORS.GREATER_THAN_OR_EQUALS,
  ],
  TIME_RANGE: [
    OPERATORS.EQUALS,
    OPERATORS.NOT_EQUALS,
    OPERATORS.LESS_THAN,
    OPERATORS.GREATER_THAN,
    OPERATORS.LESS_THAN_OR_EQUALS,
    OPERATORS.GREATER_THAN_OR_EQUALS,
    OPERATORS.WITH_IN,
    OPERATORS.OUTSIDE_OF,
  ],
  BOOLEAN: [OPERATORS.EQUALS, OPERATORS.NOT_EQUALS],
  SELECT: [
    OPERATORS.EQUALS,
    OPERATORS.NOT_EQUALS,
    OPERATORS.IS_IN,
    OPERATORS.IS_NOT_IN,
    OPERATORS.NONE_SELECTED,
    OPERATORS.ANY_SELECTED,
    OPERATORS.COUNT_EQUALS,
    OPERATORS.COUNT_NOT_EQUALS,
    OPERATORS.COUNT_LESS_THAN,
    OPERATORS.COUNT_GREATER_THAN,
    OPERATORS.COUNT_LESS_THAN_OR_EQUALS,
    OPERATORS.COUNT_GREATER_THAN_OR_EQUALS,
  ],
  MULTI_SELECT: [
    OPERATORS.EQUALS,
    OPERATORS.NOT_EQUALS,
    OPERATORS.IS_IN,
    OPERATORS.IS_NOT_IN,
    OPERATORS.NONE_SELECTED,
    OPERATORS.ANY_SELECTED,
    OPERATORS.COUNT_EQUALS,
    OPERATORS.COUNT_NOT_EQUALS,
    OPERATORS.COUNT_LESS_THAN,
    OPERATORS.COUNT_GREATER_THAN,
    OPERATORS.COUNT_LESS_THAN_OR_EQUALS,
    OPERATORS.COUNT_GREATER_THAN_OR_EQUALS,
  ],
  USER: [
    OPERATORS.EQUALS,
    OPERATORS.NOT_EQUALS,
    OPERATORS.IS_IN,
    OPERATORS.IS_NOT_IN,
    OPERATORS.NONE_SELECTED,
    OPERATORS.ANY_SELECTED,
    OPERATORS.COUNT_EQUALS,
    OPERATORS.COUNT_NOT_EQUALS,
    OPERATORS.COUNT_LESS_THAN,
    OPERATORS.COUNT_GREATER_THAN,
    OPERATORS.COUNT_LESS_THAN_OR_EQUALS,
    OPERATORS.COUNT_GREATER_THAN_OR_EQUALS,
  ],
  USER_LIST: [
    OPERATORS.EQUALS,
    OPERATORS.NOT_EQUALS,
    OPERATORS.IS_IN,
    OPERATORS.IS_NOT_IN,
    OPERATORS.NONE_SELECTED,
    OPERATORS.ANY_SELECTED,
    OPERATORS.COUNT_EQUALS,
    OPERATORS.COUNT_NOT_EQUALS,
    OPERATORS.COUNT_LESS_THAN,
    OPERATORS.COUNT_GREATER_THAN,
    OPERATORS.COUNT_LESS_THAN_OR_EQUALS,
    OPERATORS.COUNT_GREATER_THAN_OR_EQUALS,
  ],
  FILE: [OPERATORS.IS_EMPTY, OPERATORS.IS_NOT_EMPTY],
  STATE: [
    OPERATORS.EQUALS,
    OPERATORS.NOT_EQUALS,
    OPERATORS.IS_IN,
    OPERATORS.IS_NOT_IN,
  ],
  LINK: [
    OPERATORS.EQUALS,
    OPERATORS.NOT_EQUALS,
    OPERATORS.IS_IN,
    OPERATORS.IS_NOT_IN,
    OPERATORS.IS_EMPTY,
    OPERATORS.IS_NOT_EMPTY,
    OPERATORS.COUNT_EQUALS,
  ],
  CALCULATED: [
    OPERATORS.EQUALS,
    OPERATORS.NOT_EQUALS,
    OPERATORS.LESS_THAN,
    OPERATORS.GREATER_THAN,
    OPERATORS.LESS_THAN_OR_EQUALS,
    OPERATORS.GREATER_THAN_OR_EQUALS,
  ],
} as const;
