export type Operator = {
  label: string;
  value: string;
  selfClearing?: boolean;
  types: string[] | "ALL";
};

export const OPERATORS: Record<string, Operator> = {
  EQUALS: {
    label: "is",
    value: "EQUALS",
    selfClearing: false,
    types: [
      "TEXT",
      "NUMBER",
      "DATE",
      "DATE_TIME",
      "TIME",
      "BOOLEAN",
      "SELECT",
      "USER",
      "MULTI_SELECT",
      "USER_LIST",
      "CALCULATED",
      "LINK",
      "STATE",
    ],
  },
  NOT_EQUALS: {
    label: "is not",
    value: "NOT_EQUALS",
    selfClearing: false,
    types: [
      "TEXT",
      "NUMBER",
      "DATE",
      "DATE_TIME",
      "TIME",
      "BOOLEAN",
      "SELECT",
      "USER",
      "MULTI_SELECT",
      "USER_LIST",
      "CALCULATED",
      "LINK",
      "STATE",
    ],
  },
  CONTAINS: {
    label: "contains",
    value: "CONTAINS",
    selfClearing: false,
    types: ["TEXT", "SELECT", "USER", "MULTI_SELECT", "USER_LIST", "LINK"],
  },
  NOT_CONTAINS: {
    label: "does not contain",
    value: "NOT_CONTAINS",
    selfClearing: false,
    types: ["TEXT", "SELECT", "USER", "MULTI_SELECT", "USER_LIST", "LINK"],
  },
  STARTS_WITH: {
    label: "starts with",
    value: "STARTS_WITH",
    selfClearing: false,
    types: ["TEXT", "LINK"],
  },
  ENDS_WITH: {
    label: "ends with",
    value: "ENDS_WITH",
    selfClearing: false,
    types: ["TEXT", "LINK"],
  },
  NOT_STARTS_WITH: {
    label: "does not start with",
    value: "NOT_STARTS_WITH",
    selfClearing: false,
    types: ["TEXT"],
  },
  NOT_ENDS_WITH: {
    label: "does not end with",
    value: "NOT_ENDS_WITH",
    selfClearing: false,
    types: ["TEXT"],
  },
  LESS_THAN: {
    label: "less than",
    value: "LESS_THAN",
    selfClearing: false,
    types: ["NUMBER", "DATE", "DATE_TIME", "TIME", "CALCULATED"],
  },
  GREATER_THAN: {
    label: "greater than",
    value: "GREATER_THAN",
    selfClearing: false,
    types: ["NUMBER", "DATE", "DATE_TIME", "TIME", "CALCULATED"],
  },
  LESS_THAN_OR_EQUALS: {
    label: "less than or equal",
    value: "LESS_THAN_OR_EQUALS",
    selfClearing: false,
    types: ["NUMBER", "DATE", "DATE_TIME", "TIME", "CALCULATED"],
  },
  GREATER_THAN_OR_EQUALS: {
    label: "greater than or equal",
    value: "GREATER_THAN_OR_EQUALS",
    selfClearing: false,
    types: ["NUMBER", "DATE", "DATE_TIME", "TIME", "CALCULATED"],
  },
  IS_IN: {
    label: "is one of",
    value: "IS_IN",
    selfClearing: false,
    types: ["SELECT", "USER", "MULTI_SELECT", "USER_LIST", "STATE"],
  },
  IS_NOT_IN: {
    label: "is not one of",
    value: "IS_NOT_IN",
    selfClearing: false,
    types: ["SELECT", "USER", "MULTI_SELECT", "USER_LIST", "STATE"],
  },
  IS_EMPTY: {
    label: "is empty",
    value: "IS_EMPTY",
    selfClearing: true,
    types: "ALL",
  },
  IS_NOT_EMPTY: {
    label: "is not empty",
    value: "IS_NOT_EMPTY",
    selfClearing: true,
    types: "ALL",
  },
  NONE_SELECTED: {
    label: "none selected",
    value: "NONE_SELECTED",
    selfClearing: true,
    types: ["SELECT", "MULTI_SELECT", "USER_LIST", "USER", "STATE"],
  },
  ANY_SELECTED: {
    label: "any selected",
    value: "ANY_SELECTED",
    selfClearing: true,
    types: ["SELECT", "MULTI_SELECT", "USER_LIST", "USER", "STATE"],
  },
  COUNT_EQUALS: {
    label: "count equals",
    value: "COUNT_EQUALS",
    selfClearing: true,
    types: ["SELECT", "MULTI_SELECT", "USER_LIST", "USER"],
  },
  COUNT_NOT_EQUALS: {
    label: "count not equals",
    value: "COUNT_NOT_EQUALS",
    selfClearing: false,
    types: ["SELECT", "MULTI_SELECT", "USER_LIST", "USER", "TEXT"],
  },
  COUNT_LESS_THAN: {
    label: "count less than",
    value: "COUNT_LESS_THAN",
    selfClearing: false,
    types: ["SELECT", "MULTI_SELECT", "USER_LIST", "USER", "TEXT"],
  },
  COUNT_GREATER_THAN: {
    label: "count greater than",
    value: "COUNT_GREATER_THAN",
    selfClearing: false,
    types: ["SELECT", "MULTI_SELECT", "USER_LIST", "USER", "TEXT"],
  },
  COUNT_LESS_THAN_OR_EQUALS: {
    label: "count less than or equal",
    value: "COUNT_LESS_THAN_OR_EQUALS",
    selfClearing: false,
    types: ["SELECT", "MULTI_SELECT", "USER_LIST", "USER", "TEXT"],
  },
  COUNT_GREATER_THAN_OR_EQUALS: {
    label: "count greater than or equal",
    value: "COUNT_GREATER_THAN_OR_EQUALS",
    selfClearing: false,
    types: ["SELECT", "MULTI_SELECT", "USER_LIST", "USER", "TEXT"],
  },
  WITH_IN: {
    label: "with in",
    value: "WITH_IN",
    selfClearing: false,
    types: ["NUMBER", "DATE", "DATE_TIME", "TIME", "DATE_RANGE"],
  },
  OUTSIDE_OF: {
    label: "outside of",
    value: "OUTSIDE_OF",
    selfClearing: false,
    types: ["NUMBER", "DATE", "DATE_TIME", "TIME", "DATE_RANGE"],
  },
};
